// Impact + Field Manual walkthrough: enlist, earn, shop, leaderboard, guide. Fails on console errors.
// Usage: node scripts/impact.mjs [--mobile]   (needs `npx vite` running; /api is proxied to the live stack)
import { chromium } from 'playwright'
const mobile = process.argv.includes('--mobile')
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage(mobile ? { viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true } : { viewport: { width: 1440, height: 900 } })
const errors = []
page.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
page.on('pageerror', (e) => errors.push(String(e)))
const base = process.env.BASE ?? 'http://localhost:5173'
const shot = (n) => page.screenshot({ path: `/tmp/airq-shots/impact-${n}${mobile ? '-m' : ''}.png` })
const fail = (m) => { errors.push(m); console.log('FAIL', m) }
await page.addInitScript(() => localStorage.setItem('airq.player', JSON.stringify({ introSeen: true, xp: 120, missions: ['command', 'orders', 'trace', 'defend', 'call', 'general'] })))
await page.goto(base, { waitUntil: 'networkidle' })
await page.waitForTimeout(2500)
// HUD: missions done, so it points to the next real-world step
const next = await page.textContent('.hud-next')
if (!/Enlist and earn credits/.test(next ?? '')) fail(`hud next: ${next}`)
await shot('hud')
// Field Manual from "?"
await page.click('.help-btn')
await page.waitForSelector('.guide')
await shot('guide')
await page.click('.guide-nav button:has-text("Maximise")')
const before = await page.textContent('.calc-total b')
await page.fill('input[aria-label^="Plant a native tree"]', '5')
const after = await page.textContent('.calc-total b')
if (Number(after) <= Number(before)) fail(`calculator did not grow: ${before} -> ${after}`)
await shot('guide-max')
// Show me -> opens the real Earn tab with the enlist form
await page.click('.guide-nav button:has-text("Prove")')
await page.click('.guide-show button')
await page.waitForSelector('.enlist')
if (await page.isVisible('.guide')) fail('guide still open after Show me')
await page.fill('.enlist input', `UI Tester ${Math.floor(Math.random() * 900 + 100)}`)
await page.click('.enlist .primary-btn')
await page.waitForSelector('.earn', { timeout: 15000 })
await page.waitForTimeout(800)
await shot('earn')
await page.click('.actions button >> nth=0')
await page.waitForSelector('.photo-pick')
await shot('earn-pick')
await page.click('.impact .seg button:has-text("Shop")')
await page.waitForSelector('.shop')
await shot('shop')
await page.click('.impact .seg button:has-text("Leaderboard")')
await page.waitForSelector('.board li[data-me="true"]', { timeout: 15000 })
await shot('leaders')
await page.click('.leaders .seg button:has-text("States")')
await page.waitForTimeout(1500)
await shot('states')
// Escape closes the panel
await page.keyboard.press('Escape')
if (await page.isVisible('.impact')) fail('Escape did not close Impact')
const creds = await page.evaluate(() => localStorage.getItem('airq.account'))
console.log('creds', creds)
console.log(errors.length ? 'ERRORS:\n' + errors.join('\n') : 'impact: ok')
process.exitCode = errors.length ? 1 : 0
await browser.close()
